### ISSUE TITLE
Add functionality for additional plot types

### ISSUE THREAD

**Issue by tdbabas** [paul-breen/xcsv-plot#1]
Some datasets might be better represented by other plot types e.g. scatter plots. Perhaps an option to select the plot type could be added to the command line script

**Comment by paul-breen** [comment]
This is best managed by packaging up arbitrary plot `kwargs` as a `dict`.  This can then be populated by a general purpose plot-options command line option (provided as a simple JSON object and converted to a `dict`).  We can then provide convenience options (e.g., `--scatter-plot`) that package up a set of plot-options.
